spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc;mysql;//localhost:3306/book?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

    #连接池配置
    hikari:
      #最小空闲连接数量
      minimum-idle: 5
      #空闲连接最大存活时间（毫秒）
      idle-timeout: 180000
      #连接池最大连接数，默认 10
      maximum-pool-size: 15
      #连接事务是否自动提交
      auto-commit: true
      #连接池名称
      pool-name: MyHikariCP
      #连接池中连接的最长生命周期：默认1800000（30分钟）
      max-lifetime: 1800000
      #数据库连接超时时间（默认30秒）
      connection-timeout: 30000
      #测试连接的最长时间
      validation-timeout: 5000

### mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath;/mapper/*Mapper.xml
  #实体扫描，多个package用（，）隔开
  type-aliases-package: com.example.book.entity.po
  #全局配置
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #刷新mapper
    refresh-mapper: true
    #驼峰下划线转换
    db-column-underline: false

http:
  # 设置连接超时时间，单位为毫秒
  connectTimeout: 10000
  # 设置读取超时时间，单位为秒
  readTimeout: 10
  # 设置写超时时间，单位为秒
  writeTimeout: 10
  # 最大空闲连接数
  maxIdleConnections: 20
  # 长连接超时时间，单位为分钟
  keepAliveDuration: 5